v <-c(3,8,4,5,0,11, -9, 304)
sort.result <-sort(v)
print(sort.result)
revsort.result <-sort(v, decreasing = TRUE)
v <-c("Red","Blue","yellow","violet")
sort.result <-sort(v)
print(sort.result)
revsort.result <-sort(v, decreasing = TRUE)
print(revsort.result) 